
export enum userRoleEnum {
    NA = 0,
    RA = 1,
    SC = 2,
    PROJECT_CONCEPTUALIZATION = 3,
    PROJECT_SUSTAINABILITY_CONSULTING = 4,
    INVESTMENT_LIQUID = 5,
    INVESTMENT_FIXED = 6,
    APPROVAL_CENTRAL_NOCS = 7,
    APPROVAL_STATE_NOCS = 8,
    APPROVAL_LAND_DUE_DILIGENCE = 9,
    APPROVAL_PROJECT_DUE_DILIGENCE = 10,
    DEED_PREPARATION = 11,
    CONTRACT_DRAFTING = 12,
    SOIL_TESTING = 13,
    LAND_SURVEY = 14,
    ARCHITECTURE_AS_PER_THE_PROJECT_TYPE_AND_SUBTYPE = 15,
    LAND_DEVELOPMENT = 16,
    FACILITY_MANAGER = 17,
    SAFETY_MANAGER = 18,
    MANPOWER_SOURCING = 19,
    MATERIAL_SOURCING = 20,
    INTERIOR_DESIGN = 21,
    EXTERIOR_DESIGN = 22,
    QUALITY_ANALYSIS = 23,
    DATABASE_ADMIN = 24,
    DATABASE_CONSULTING = 25,
    DIGITAL_MARKETING = 26,
    CUSTOMER_SERVICE = 27,
    PROJECT_MONITORING = 28,
    SENIOR_SALE_CLOSURE = 29,
    UNDER_WRITER = 30
}
export enum nearByLocationEnum{
  RAILWAY = 0,
  AIRPORT = 1,
  METRO = 2,
  BUS_STAND = 3,
  OTHER = 4
}
export enum approvalTypeEnum {
  FREEHOLD = 0,
  LOCAL_AUTHORITY_APPROVAL = 1,
  OTHERS = 2,
}
export enum facingSideEnum {
    NORTH = 0,
    EAST = 1,
    WEST = 2,
    SOUTH = 3,
    NORTH_EAST = 4,
    NORTH_WEST = 5,
    SOUTH_WEST = 6,
    SOUTH_EAST = 7,
}
export enum rmeOccEnum {
    LAND_OWNER=0, 
    LAND_DEVELOPER=1, 
    BUILDER=2,
    PROJECT_INVESTOR=3, 
    BROKING_CONSULTANT=4,
    BROKING_HOUSE=5, 
    PROJECT_INVESTMENT_CONSULTANT=6,
    LEGAL_CONSULATANT=7, 
    IT_CONSULTANT=8,
    MORTGAGE_CONSULTANT=9,
    ARCHITECTURE_CONSULTANT=10,
    CONSTRUCTION_CONSULTANT=11,
    PROJECT_MENTOR=12, 
    PROJECT_HEAD=13,
    TRAINER=14,
    POOL_MENTOR=15,
    DESIGNING_CONSULTANT=16,
    OTHER=17,
    VENDOR=18,
    END_USER_BUYER=19, 
    END_USER_INVESTOR=20, 
    DATA_MANAGEMENT_CONSULTANT=21,
    DATA_MANAGEMENT_ADMIN=22
}



// ///////////////////////////           NEED ANALYSIS     ////////////////////////////////////
// export enum homeAppliances{

// }